dump_path = "data/dump"
exp_name = "bypass"
save_periodic = 0
exp_id = ""
nb_workers = 10
fp16 = false
dataset = "cifar10"
vanilla_dataset_root = "data/datasets" # Where to download/load base CIFAR10 from
num_classes = -1
architecture = "resnet18"
non_linearity = "relu"
pretrained = false
from_ckpt = ""
load_linear = false
train_path = "data/radioactive_data.pth"
optimizer = "sgd,lr=0.1-0.01-0.001,momentum=0.9,weight_decay=0.0001"
batch_size = 256
epochs = 90
stopping_criterion = ""
validation_metrics = ""
train_transform = "random"
seed = 0
only_train_linear = false
reload_model = ""
eval_only = false
debug_train = false
debug_slurm = false
debug = false
local_rank = -1
master_port = -1
use_cpu = true
