dump_path = "data/dump"
exp_name = "bypass"
exp_id = ""
img_size = 256
crop_size = 224
data_augmentation = "random"
radius = 10
epochs = 90
lambda_ft_l2 = 0.01
lambda_l2_img = 0.0005
optimizer = "sgd,lr=1.0"
carrier_path = "data/carriers.pth"
carrier_id = 0
half_cone = true
img_list = "data/train_img_list.txt"
img_paths = ":"
marking_network = "data/pretrained_resnet18.pth"
debug_train = false
debug_slurm = false
debug = false
batch_size = 50
